// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using PropertEase.Infrastructure;

#nullable disable

namespace PropertEase.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260421000000_DropIsActiveColumnAddMissingIndexes")]
    partial class DropIsActiveColumnAddMissingIndexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
